com.huawei.hms.maps.model.BitmapDescriptor
com.huawei.hms.maps.model.Cap
com.huawei.hms.maps.model.LatLng
com.huawei.hms.maps.model.LatLngBounds
com.huawei.hms.maps.model.MapStyleOptions
com.huawei.hms.maps.model.PatternItem
com.huawei.hms.maps.model.PinConfig
