name: Test

on:
  workflow_call:

jobs:
  unit-test:
    name: unit tests
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7.0.0

      - name: Setup Java ☕
        uses: actions/setup-java@v5.3.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle 🐘
        uses: gradle/actions/setup-gradle@v6.2.0

      - name: Run Jacoco Task
        run: ./gradlew jacocoTestReport --stacktrace

      - name: Upload test results artifact
        uses: actions/upload-artifact@v7.0.1
        if: always()
        with:
          name: unit-test-report
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*
            build/reports/*
          if-no-files-found: warn